#!/bin/bash
 
#SBATCH --job-name=serial

### how much time, this job takes < one minute, we just put 30 mins
#SBATCH --time=00:30:00

### how much memory, 2 GB is plenty for this
#SBATCH --mem=32G

### how many processes in this job
#SBATCH --ntasks=1

### change the 1 below to match the # of cores needed
#SBATCH --cpus-per-task=1

#SBATCH --account=fit3143
#SBATCH --qos=fit3143
##SBATCH --partition=gpu

./a.out

exit 0
